# Generated by Django 5.2.6 on 2025-09-05 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_count', models.IntegerField(editable=False, null=True)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('prompt', models.TextField()),
                ('ai_response', models.TextField(editable=False)),
                ('chat_id', models.CharField(editable=False, max_length=1000, primary_key=True, serialize=False)),
                ('token_count', models.IntegerField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.chat')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chatbot_app.session')),
            ],
        ),
    ]
