# Generated by Django 5.2.6 on 2025-09-04 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('prompt', models.CharField(max_length=1000)),
                ('ai_response', models.CharField(max_length=1000)),
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('token_count', models.IntegerField(null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot_app.chat')),
            ],
        ),
    ]
