# Generated by Django 5.2.6 on 2025-09-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0002_alter_chat_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='ai_response',
            field=models.CharField(editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.CharField(editable=False, max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='prompt',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='chat',
            name='token_count',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
